name: Docker Push

on: [push, workflow_dispatch]

jobs:
  build:
    name: Docker Push
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: shish2k/chapterss
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
