name: Docker Push

on: [push]

jobs:
  build:
    name: Docker Push
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: Deploy
        uses: shish/watchtower-update@main
        with:
          url: https://watchtower.shish.io/v1/update
          api_token: ${{ secrets.WATCHTOWER_TOKEN }}
          images: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}
